debug:
  container_name: sailsSample_debug
  image: node:4
  command: "/bin/bash -l"

  working_dir: /sailsSample
  volumes:
    - ./:/sailsSample
  ports:
    - "1337:1337"


buildDev:
  container_name: sailsSample_buildDev
  image: trunk/sails_env
  command: "/bin/bash -l -c 'npm i && node_modules/.bin/grunt build'"

  working_dir: /sailsSample
  volumes:
    - ./:/sailsSample

buildProd:
  container_name: sailsSample_buildProd
  image: trunk/sails_env
  command: "/bin/bash -l -c 'npm i && node_modules/.bin/grunt prod'"

  working_dir: /sailsSample
  volumes:
    - ./:/sailsSample

test:
  container_name: sailsSample_test
  image: trunk/sails_env
  command: "/bin/bash -l -c 'node_modules/.bin/grunt test'"
  ports:
    - "1338:1338"

  working_dir: /picklete
  volumes:
    - ./:/picklete

web:
  container_name: sailsSample
  image: trunk/sails_env
  command: "/bin/bash -l -c 'npm start'"
  environment:
    PORT: "1337"
    NODE_ENV: "production"
    DOMAIN_HOST: "localhost:1337"

  ports:
    - "1337:1337"

  working_dir: /sailsSample
  volumes:
    - ./:/sailsSample
  external_links:
    - mysql

  restart: always


mysql:
  container_name: mysql
  image: dgraziotin/mysql

  ports:
    - "3306:3306"
  environment:
    MYSQL_ADMIN_PASS: "root"
    MYSQL_USER_NAME: "nodejsSample"
    MYSQL_USER_DB: "nodejsSample"
    MYSQL_USER_PASS: "nodejsSample"
    CREATE_MYSQL_BASIC_USER_AND_DB: "true"

  volumes:
    - ../database:/var/lib/mysql/

  restart: always
